# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bba075701c97635737da3f929dfddbdcd338e0bcc24bb90b6333a912e3a61dcff65e9d564751591132b965b55d5fe6ec68404aac6bafc948af2c9e7b15d5379

test:
  secret_key_base: 85310c095e0121be979fdac6db0e2543fa799a9aceed314e84f7f60ee1b7e619177bbf4b70193babcfb0e15814051ced9bb70c74fc6bc128fcd9a23aa6da3605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
